services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - /home/${USER}/media/files:/usr/share/nginx/html:ro
      - /home/${USER}/media/config/nginx-config/:/etc/nginx/conf.d/
    restart: unless-stopped

  sftp:
    image: atmoz/sftp
    container_name: sftp
    ports:
      - "2222:22"
    volumes:
      - /home/${USER}/media/files/uploads:/home/${SFTP_USER}/
    command: ${SFTP_USER}:${SFTP_PASS}
    restart: unless-stopped

  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest              
    container_name: cloudflare                
    hostname: cloudflare-tunnel                      
    restart: unless-stopped                           
    network_mode: "host"                              
    command: tunnel run                               
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_KEY}

